const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../background.js'),'utf8');
const db={},writes=[];
const account={id:'company-a',kind:'company',assetInventory:{buildings:[{ref:'way/1',raw:{ref:'way/1',chunkId:'15/10/20'}},{ref:'way/2',raw:{ref:'way/2',chunkId:'15/11/20'}}]}};
db.crcc_snapshot_v4={accounts:{company:account}};
const ctx=vm.createContext({URL,Date,console,btoa,fetch:async(url,init)=>{writes.push({url,body:JSON.parse(init.body)});return{ok:true};},chrome:{storage:{local:{get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,db[k]])),set:async patch=>Object.assign(db,patch)}}}});
vm.runInContext(src.slice(0,src.indexOf('async function recordHistory(')),ctx);
vm.runInContext(src.slice(src.indexOf('// ---- rename learning / only game write ----'),src.indexOf('// ---- 5-minute automatic refresh ----')),ctx);
const run=x=>vm.runInContext(x,ctx);
ctx.learning={active:true,marker:'CRCC_BUILDING_TEST',startedAt:Date.now(),ref:'way/1',scope:'company',accountId:'company-a',asset:{chunkId:'15/10/20'}};
ctx.obs={method:'POST',url:'https://play.capitalrift.com/api/building/rename',body:{ref:'way/1',chunkId:'15/10/20',name:'CRCC_BUILDING_TEST'}};
assert.equal(run('deriveBuildingRenameTemplate({...obs,body:{...obs.body,ref:"way/9"}},learning)'),null,'marker on another building must not teach a template');
assert.equal(run('deriveBuildingRenameTemplate({...obs,body:{...obs.body,chunkId:"15/99/99"}},learning)'),null,'unmatched chunk cannot be frozen into template');
const template=run('deriveBuildingRenameTemplate(obs,learning)');assert(template);db.crcc_building_rename_template_v1=template;
ctx.gameGet=async url=>url==='/me'?{piloting:{companyId:'company-a'}}:{assets:[{kind:'property',ref:'way/2',chunkId:'15/11/20',label:'Offices'}]};
(async()=>{
 await assert.rejects(run('performBuildingRename("company","company-a","way/9","New")'),/not confirmed/);
 await assert.rejects(run('performBuildingRename("character","company-a","way/2","New")'),/not confirmed/);
 db.crcc_building_rename_template_v1={...template,accountId:'other'};
 await assert.rejects(run('performBuildingRename("company","company-a","way/2","New")'),/separately/);
 db.crcc_building_rename_template_v1=template;
 await run('performBuildingRename("company","company-a","way/2","New name")');
 assert.equal(writes.length,1);assert.deepEqual(writes[0].body,{ref:'way/2',chunkId:'15/11/20',name:'New name'});
 assert.equal((await run('performBuildingRename("company","company-a","way/2","Offices")')).skipped,true);
 assert.equal(writes.length,1,'already-correct name cannot issue a write');
 ctx.gameGet=async url=>url==='/me'?{piloting:{companyId:'other'}}:{assets:[{kind:'property',ref:'way/2',chunkId:'15/11/20'}]};
 await assert.rejects(run('performBuildingRename("company","company-a","way/2","Change")'),/matching account/);
 const ui=fs.readFileSync(path.join(__dirname,'../content.js'),'utf8');const panel=vm.createContext({});vm.runInContext(ui.slice(ui.indexOf('  function retailDemandLines('),ui.indexOf('  async function captureVisibleShopHealth(')),panel);
 panel.sample='Appeal grade 82 / 100\nWhat your neighbourhood wants\nSneakers\nSaplings\nNobody nearby sells\nNails\nRestocking\n$42/min';
 const signals=vm.runInContext('retailDemandLines(sample)',panel);
 assert.deepEqual([...signals.localWants],['Sneakers','Saplings']);assert.deepEqual([...signals.localGaps],['Nails']);
 assert.equal(vm.runInContext('retailDemandLines("Gross / min\\n$40")',panel).localWants,undefined,'missing section preserves old observed demand');
 assert.match(ui,/Game layout appeal/);assert.match(ui,/Command Center portfolio grade/);
 console.log('PASS: building rename learns exact ref/chunk, confirms owned deed and active account, skips correct names; observed demand/appeal kept separate');
})().catch(e=>{console.error(e);process.exitCode=1;});
