const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../background.js'),'utf8');
const ui=fs.readFileSync(path.join(__dirname,'../content.js'),'utf8');
assert.match(ui,/state\.page==='transactions'\)checkTransactionCompany\(\)/);
assert.match(ui,/state\.page==='transactions'\)checkTransactionCompany\(\);},15000/);
assert.match(ui,/state\.page==='transactions'&&state\.data\?\.identity\?\.companyId&&state\.data\?\.accounts\?\.company\)state\.scope='company'/);
const db={};
const ctx=vm.createContext({URL,Date,console,CRCCTransactions:require('../transaction-log.js'),chrome:{storage:{local:{get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,db[k]])),set:async rows=>Object.assign(db,rows)}}}});
vm.runInContext(src.slice(0,src.indexOf('async function recordHistory(')),ctx);
vm.runInContext(src.slice(src.indexOf('async function refreshData('),src.indexOf('function scoutRoomSummary(')),ctx);
ctx.recordHistory=async()=>{};ctx.updatePropertyBuyers=async()=>{};ctx.mergeMarketIntel=async()=>{};
let pilot={companyId:'a',name:'Alpha'},reads=[];
ctx.gameGet=async p=>{
  reads.push(p);
  if(p==='/me')return{playerId:'person',piloting:pilot};
  if(p==='/company/mine')return{companies:[{id:'a',name:'Alpha'},{id:'b',name:'Beta'}]};
  if(p==='/game/person')return{playerId:'person'};
  if(p==='/game/a'||p==='/game/b')return{playerId:p.slice(-1),bank:{accounts:[{id:'main',name:'Company cash',transactions:[{id:p.slice(-1),ts:1000,kind:'send',amount:-100,desc:'Transfer'}]}]}};
  throw Error('optional');
};
(async()=>{
  let s=await vm.runInContext('refreshData()',ctx);
  assert.equal(s.identity.companyId,'a');assert.equal(s.accounts.company.id,'a');
  pilot={companyId:'b'};reads=[];
  s=await vm.runInContext('refreshData()',ctx);
  assert.equal(s.identity.companyId,'b');assert.equal(s.accounts.company.id,'b');assert.equal(s.identity.companyName,'Beta');
  assert.ok(reads.includes('/game/b'));assert.ok(!reads.includes('/game/a'));
  assert.equal(db.crcc_company_transaction_log_v1['person:a'].rows[0].gameId,'a');
  assert.equal(db.crcc_company_transaction_log_v1['person:b'].rows[0].gameId,'b');
  pilot={name:'Unknown new pilot'};reads=[];
  s=await vm.runInContext('refreshData()',ctx);
  assert.equal(s.identity.companyId,null);assert.equal(s.accounts.company.id,'b');
  assert.equal(s.diagnostics.identity,'partial');assert.ok(!reads.includes('/game/b'));
  pilot=null;s=await vm.runInContext('refreshData()',ctx);
  assert.equal(s.identity.companyId,null);assert.equal(s.accounts.company.id,'b');
  console.log('PASS: switching companies isolates bank logs, resolves new name, and unknown pilot stays cached read-only');
})().catch(e=>{console.error(e);process.exitCode=1;});
