const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../background.js'),'utf8');
const db={};
const ctx=vm.createContext({URL,Date,Math,Number,console,btoa:s=>Buffer.from(String(s),'binary').toString('base64'),setTimeout,clearTimeout,fetch:async()=>({ok:true,text:async()=>'{"purchasePrice":123}'}),chrome:{storage:{local:{get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,db[k]])),set:async patch=>Object.assign(db,patch)}}}});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../land-buyer.js'),'utf8'),ctx);
vm.runInContext(src.slice(0,src.indexOf('async function recordHistory(')),ctx);
vm.runInContext(src.slice(src.indexOf('function observedFootprintBounds('),src.indexOf('function extractBuildingIntel(')),ctx);
vm.runInContext('var viewportSurveyCache=new Map();',ctx);
vm.runInContext(src.slice(src.indexOf('// ---- rename learning / only game write ----'),src.indexOf('// ---- 5-minute automatic refresh ----')),ctx);
const run=code=>vm.runInContext(code,ctx);
ctx.learning={active:true,startedAt:Date.now(),scope:'company',accountId:'company-a',parcel:{ref:'parcel/abc123',id:'abc123',parcelId:'abc123',landId:'abc123',entityType:'land',source:'observed-game-land',chunkId:'15/10/20',areaM2:5000,purchasePrice:100,listing:{id:'listing-one',listingId:'listing-one',kind:'sale',forSale:true,price:100}}};
ctx.obs={method:'POST',url:'https://play.capitalrift.com/api/land/buy/abc123',body:{parcelId:'abc123',chunkId:'15/10/20',listingId:'listing-one',price:100,companyId:'company-a'}};
const template=run('deriveLandBuyTemplate(obs,learning)');
assert(template,'official selected parcel request should be learnable');
assert.equal(template.mapping.parcelId,'parcelId');
assert.equal(template.mapping.chunkId,'chunkId');
assert.match(template.urlTemplate,/__CRCC_/);
ctx.other={ref:'parcel/xyz789',id:'xyz789',parcelId:'xyz789',landId:'xyz789',entityType:'land',source:'observed-game-land',chunkId:'15/11/20',purchasePrice:250,listing:{id:'listing-two',listingId:'listing-two',kind:'sale',forSale:true,price:250}};
ctx.template=template;
assert.equal(run('buildLandBuyUrl(template,other)'),'https://play.capitalrift.com/api/land/buy/xyz789');
const body=run('buildLandBuyBody(template,other)');
assert.equal(body.parcelId,'xyz789');assert.equal(body.chunkId,'15/11/20');assert.equal(body.listingId,'listing-two');assert.equal(body.companyId,'company-a');
assert.equal(run('validateLandBuyTemplate(template)'),true,'learned request has a dynamic parcel identity and mapped purchase fields');
ctx.invalidTemplate={...template,mapping:{},urlMap:{}};assert.equal(run('validateLandBuyTemplate(invalidTemplate)'),false,'unmapped parcel action cannot authorize a batch');
ctx.unrelated={method:'POST',url:'https://play.capitalrift.com/api/land/buy/not-this-one',body:{parcelId:'not-this-one'}};
assert.equal(run('deriveLandBuyTemplate(unrelated,learning)'),null,'an unrelated parcel purchase cannot train the template');
ctx.edit={method:'POST',url:'https://play.capitalrift.com/api/land/edit/abc123',body:{parcelId:'abc123',action:'edit-land'}};
assert.equal(run('deriveLandBuyTemplate(edit,learning)'),null,'land edits cannot teach a purchase');
(async()=>{
 const ref='parcel/abc123';db.crcc_scout_parcels_v1={[ref]:{id:ref,chunkId:'15/10/20',areaM2:5000,owner:null,purchasePrice:100,listing:{id:'listing-one',listingId:'listing-one',kind:'sale',forSale:true,price:100},observedAt:Date.now()}};
 db.crcc_land_buy_learning_v1={active:true,startedAt:Date.now(),scope:'company',accountId:'company-a',status:'waiting'};
 ctx.purchaseRequest={...ctx.obs,kind:'request'};
 await run('captureLandLearning(purchaseRequest)');
 assert.equal(db.crcc_land_buy_template_v1,undefined,'request alone never completes learning');
 assert.equal(db.crcc_land_buy_learning_v1.status,'verifying');
 ctx.failedResponse={kind:'response',method:'POST',url:ctx.obs.url,status:409,data:{error:'already owned'}};
 await run('captureLandLearning(failedResponse)');assert.equal(db.crcc_land_buy_template_v1,undefined,'failed purchase cannot teach an action');
 await run('captureLandLearning(purchaseRequest)');
 ctx.purchaseSuccess={kind:'response',method:'POST',url:ctx.obs.url,status:200,data:{ok:true}};
 await run('captureLandLearning(purchaseSuccess)');
 assert.equal(db.crcc_land_buy_learning_v1.status,'learned');assert(db.crcc_land_buy_template_v1,'successful response teaches the reusable action');
 assert.equal(db.crcc_scout_parcels_v1[ref].myOwned,true,'normally purchased parcel is marked owned');
 db.crcc_land_buy_learning_v1={active:true,startedAt:Date.now(),scope:'company',accountId:'company-a',status:'waiting'};
 delete db.crcc_land_buy_template_v1;
 await run('captureLandLearning(purchaseRequest)');
 assert.equal(db.crcc_land_buy_learning_v1.status,'waiting','already owned parcel cannot be used for new learning');
 assert.equal(db.crcc_land_buy_template_v1,undefined);
 db.crcc_scout_parcels_v1[ref].myOwned=false;
 ctx.liveWorld={parts:[{chunks:{'15/10/20':{chunkId:'15/10/20',parcels:[{id:ref,chunkId:'15/10/20',centroid:[127,37],areaM2:5000,owner:null}]}}}]};
 ctx.fetch=async()=>({ok:true,json:async()=>ctx.liveWorld});
 ctx.storeObservation=async()=>{};
 ctx.scoutTileBounds=()=>({north:38,south:36,east:128,west:126});
 const noOffer=await run('resolveLandParcels(["parcel/abc123"])');
 assert.equal(noOffer.resolvedRefs.length,1,'fresh parcel is present');
 assert.equal(Object.keys(noOffer.liveOffers).length,0,'cached sale offer cannot authorize a purchase');
 ctx.landDetail={kind:'response',method:'GET',url:'https://play.capitalrift.com/api/land/abc123',status:200,data:{parcelId:'abc123',owner:null,purchaseOffer:{price:125}}};
 db.crcc_snapshot_v4={identity:{companyId:'company-a'}};
 await run('observeLandDetail(landDetail)');
 assert.equal(db.crcc_scout_parcels_v1[ref].listing.price,125,'official land panel purchase offer enriches the selected parcel');
 ctx.fetch=async(url)=>url.endsWith('/api/world')?{ok:true,json:async()=>ctx.liveWorld}:{ok:true,status:200,json:async()=>ctx.landDetail.data};
 const panelOffer=await run('resolveLandParcels(["parcel/abc123"])');
 assert.equal(panelOffer.liveOffers[ref].listing.price,125,'refresh reuses an observed game land detail URL and verifies its parcel ID');
 ctx.landDetail.data={parcelId:'abc123',owner:null};
 const missingPanelOffer=await run('resolveLandParcels(["parcel/abc123"])');
 assert.equal(Object.keys(missingPanelOffer.liveOffers).length,0,'old panel offer is not live if the current panel omits it');
 ctx.liveWorld.parts[0].chunks['15/10/20'].parcels[0].listing={kind:'sale',price:125};
 const freshOffer=await run('resolveLandParcels(["parcel/abc123"])');
 assert.equal(freshOffer.liveOffers[ref].listing.price,125,'live offer price replaces cached purchase price');
 ctx.fetch=async()=>({ok:true,text:async()=>'{"ok":false,"error":"not for sale"}'});
 const rejected=await run('performLandPurchase(template,other)');
 assert.equal(rejected.ok,false,'HTTP 200 with a game error must not mark parcel purchased');
 console.log('PASS: learned action remaps IDs, ignores land edits and failures, waits for success, rejects owned land');
})().catch(e=>{console.error(e);process.exitCode=1;});
