const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const src=fs.readFileSync(require('node:path').join(__dirname,'../background.js'),'utf8');
const storage={};
const ctx=vm.createContext({URL,Date,console,chrome:{storage:{local:{get:async()=>storage,set:async v=>Object.assign(storage,v)}}}});
vm.runInContext(src.slice(0,src.indexOf('async function recordHistory(')),ctx);
vm.runInContext(src.slice(src.indexOf('// ---- live market intelligence'),src.indexOf('let fullMarketScanRunning=')),ctx);
vm.runInContext(src.slice(src.indexOf('function objectWalk('),src.indexOf('async function storeObservation(')),ctx);
vm.runInContext(src.slice(src.indexOf('async function storeObservation('),src.indexOf('async function saveShopHealth(')),ctx);
const run=s=>vm.runInContext(s,ctx);
(async()=>{
  ctx.shares={listings:[{companyId:'id-a',name:'Same Name',price:10,backing:5,changePct:2,holders:4,floatBps:1000},{companyId:'id-b',name:'Same Name',price:20,backing:6,changePct:3,holders:5,floatBps:2000}]};
  assert.equal(run('normalizeMarketCatalog({},shares).length'),2);
  assert.equal(run('extractMarketIntel(shares).length'),2);
  ctx.book={companyId:'id-a',bids:[{price:9,qty:3},{price:8,qty:26}],asks:[{price:10,qty:8},{price:12,qty:9}],last:10,backing:5};
  assert.equal(run('marketBookMetrics(book,null).bid'),9);
  assert.equal(run('marketBookMetrics(book,null).askDepth'),17);
  ctx.hist={companyId:'id-a',name:'Same Name',window:'30d',last:10,changePct:5996.9,volume:1783203,closes:[1,10]};
  assert.equal(run("marketBookMetrics(null,hist,'30d').dayMove"),undefined);
  assert.equal(run("marketBookMetrics(null,hist,'30d').change30dPct"),5996.9);
  assert.equal(run("extractMarketIntel(hist,{window:'30d'})[0].volume"),null);
  ctx.ipo=[{listingId:'offer-a',companyId:'id-a',name:'Same Name',floorPrice:24.76,sharesOffered:1000000,endsAt:Date.now()+100000,demand:5,bidders:2},{listingId:'offer-b',companyId:'id-b',name:'Same Name',floorPrice:60,sharesOffered:1000000},{listingId:'offer-a',companyId:'id-a',name:'Same Name',floorPrice:24.76,sharesOffered:1000000}];
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/game/me/shares/ipo',ts:1000,data:ipo})");
  assert.equal(Object.keys(storage.crcc_ipo_market_v1).length,2);
  ctx.ipo=[{listingId:'offer-a',companyId:'id-a',name:'Same Name',floorPrice:25,sharesOffered:1000000}];
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/game/me/shares/ipo',ts:500,data:ipo})");
  assert.equal(storage.crcc_ipo_market_v1['offer-a'].floorPrice,24.76);
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/game/me/shares/ipo',ts:2000,data:[]})");
  assert.equal(Object.keys(storage.crcc_ipo_market_v1).length,2);
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/game/me/shares/book/id-a',ts:2000,data:book})");
  assert.equal(storage.crcc_market_intel_v4['company:id-a'].bidDepth,29);
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/game/me/shares/history/id-a?window=30d',ts:2100,data:hist})");
  const row=storage.crcc_market_intel_v4['company:id-a'];assert.equal(row.bid,9);assert.equal(row.ask,10);assert.equal(row.change30dPct,5996.9);assert.equal(row.dayMove,undefined);assert.equal(row.volume,undefined);assert.equal(row.volume30d,1783203);
  console.log('PASS: duplicate company names with distinct IDs, book depth and spread, IPO dedupe/stale/partial, 30d history isolation and observation order');
})().catch(e=>{console.error(e);process.exitCode=1;});
