const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const content=fs.readFileSync(path.join(__dirname,'../content.js'),'utf8');
const panel={isConnected:true,textContent:'PROPERTY EDIT\nROOM OPERATIONS\nGross 106\nTakings $2 /min',get innerText(){reads++;return this.textContent;}};
const other=Array.from({length:500},()=>({textContent:'Other menu with many controls',get innerText(){throw Error('unrelated game layout read');}}));
let reads=0,queries=0,shopListReads=0;
const shops=[{name:'Gross 106',id:106},{name:'Gross 107',id:107}];
const context=vm.createContext({document:{querySelectorAll:()=>{queries++;return [...other,panel];}},host:{contains:()=>false},shopName:x=>x.name,baseShopRows:()=>{shopListReads++;return shops;},account:()=>({id:'company'}),Map,Set,Array});
vm.runInContext(content.slice(content.indexOf('  let shopPanelCache='),content.indexOf('  function retailDemandLines(')),context);
assert.equal(vm.runInContext('visibleShopFromPage().row.id',context),106);
assert.equal(reads,1,'read layout only on the matching shop panel');
assert.equal(shopListReads,1);
assert.equal(vm.runInContext('visibleShopFromPage().row.id',context),106);
assert.equal(queries,1,'reuse attached panel on the next poll');
assert.equal(reads,2,'poll only the visible panel once');
panel.isConnected=false;
assert.equal(vm.runInContext('visibleShopFromPage().row.id',context),106);
assert.equal(queries,2,'detached React panel is rediscovered');
panel.isConnected=true;
panel.textContent='Gross 107\nGross / min\n$1,006.35\nFoot traffic\nx2.41';
assert.equal(vm.runInContext('visibleShopFromPage().row.id',context),107,'shop health panel works without property editor headings');
panel.textContent+='\nGross 106';
assert.equal(vm.runInContext('visibleShopFromPage()',context),null,'ambiguous visible shops are never guessed');

let storageHandler,storageGets=0,redraws=0,scheduled=[];
const ui=vm.createContext({state:{open:true,page:'overview',shopHealth:{},data:{accounts:{company:{}}},scope:'company'},chrome:{storage:{onChanged:{addListener:fn=>storageHandler=fn}},runtime:{sendMessage:async()=>{storageGets++;return{ok:true};}}},setTimeout:fn=>{scheduled.push(fn);return scheduled.length;},mergeGet:()=>{},render:()=>{redraws++;},scheduleScout:()=>{}});
vm.runInContext(content.slice(content.indexOf('  let storageSyncTimer='),content.indexOf('  function updateChrome(')),ui);
storageHandler({crcc_shop_health_v4:{newValue:{fresh:true}}},'local');
assert.equal(storageGets,0,'health update does not fetch the whole snapshot');
assert.equal(redraws,0,'overview is not redrawn for shop health changes');
assert.equal(ui.state.shopHealth.fresh,true);
storageHandler({crcc_snapshot_v4:{}},'local');
storageHandler({crcc_hourly_v4:{},crcc_market_intel_v4:{}},'local');
assert.equal(scheduled.length,1,'related storage notifications coalesce');
ui.state.open=false;
const finish=scheduled.shift()();
Promise.resolve(finish).then(()=>{
  assert.equal(storageGets,1);
  assert.equal(redraws,0,'closed panel is not rebuilt for background changes');
}).catch(e=>{console.error(e);process.exitCode=1;});

const background=fs.readFileSync(path.join(__dirname,'../background.js'),'utf8');
const bridge=fs.readFileSync(path.join(__dirname,'../bridge.js'),'utf8');
const idle=[],tileEvents=[];let tileDecodes=0;
const bridgeCtx=vm.createContext({window:{fetch:()=>{}},requestIdleCallback:fn=>idle.push(fn),setTimeout:fn=>idle.push(fn),globalThis:{CRCCScoutTile:{decode:()=>{tileDecodes++;return[{ref:'way/1'}];}}},emit:x=>tileEvents.push(x),URL,ArrayBuffer,Map,Number,Date});
vm.runInContext(bridge.slice(bridge.indexOf('  const nativeFetch='),bridge.indexOf('  window.fetch=async function(')),bridgeCtx);
bridgeCtx.fakeRes={ok:true,status:200,headers:{get:()=>null},clone:()=>({arrayBuffer:async()=>new ArrayBuffer(16)})};
bridgeCtx.tileUrl='https://play.capitalrift.com/api/maptile/15/21617/18265.mvt';
vm.runInContext('observeTile(fakeRes,tileUrl)',bridgeCtx);
Promise.resolve().then(()=>{
  assert.equal(tileDecodes,0,'Scout tile parsing waits for browser idle time');
  assert.equal(idle.length,1);
  idle.shift()();
  assert.equal(tileDecodes,1);
  assert.equal(tileEvents[0].data.buildings[0].ref,'way/1');
}).catch(e=>{console.error(e);process.exitCode=1;});
const db={},writes=[];
const ctx=vm.createContext({Date,JSON,Object,chrome:{storage:{local:{get:async key=>({[key]:db[key]}),set:async patch=>{Object.assign(db,patch);writes.push(patch);}}}},HEALTH_KEY:'health',num:x=>Number(x)||0,trimRow:x=>x});
vm.runInContext(background.slice(background.indexOf('async function saveShopHealth('),background.indexOf('async function saveNavigationAnchor(')),ctx);
(async()=>{
  ctx.first={accountId:'a',shopKey:'s',captured:true,footTraffic:2.4,at:100,appealAt:100,localDemandAt:100};
  await vm.runInContext('saveShopHealth(first)',ctx);
  assert.equal(writes.length,1);
  ctx.second={...ctx.first,at:200,appealAt:200,localDemandAt:200};
  await vm.runInContext('saveShopHealth(second)',ctx);
  assert.equal(writes.length,1,'timestamp-only shop poll does not rewrite all shop health');
  ctx.second.footTraffic=2.5;
  await vm.runInContext('saveShopHealth(second)',ctx);
  assert.equal(writes.length,2,'real changes are still stored');
  console.log('PASS: shop panel cached, unrelated menu layout untouched, detached panel recovered, identical health poll skipped');
})().catch(e=>{console.error(e);process.exitCode=1;});
