const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../background.js'),'utf8');
const {plan}=require('../rename-plan.js');
const {derive}=require('../shop-metrics.js');
const db={},ctx=vm.createContext({URL,Date,console,chrome:{storage:{local:{get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,db[k]])),set:async rows=>Object.assign(db,rows)}}}});
vm.runInContext(source.slice(0,source.indexOf('async function recordHistory(')),ctx);
vm.runInContext(source.slice(source.indexOf('async function refreshData('),source.indexOf('function scoutRoomSummary(')),ctx);
vm.runInContext(source.slice(source.indexOf('function buildRenameUrl('),source.indexOf('async function beginRenameLearning(')),ctx);
ctx.scoutAnchor=x=>x;ctx.recordHistory=async()=>{};ctx.updatePropertyBuyers=async()=>{};ctx.mergeMarketIntel=async()=>{};
const game=(id)=>({playerId:id,cash:1000,netWorth:5000,income:{grossPerMin:50,netPerMin:25},shops:[{id:'stable-1',name:'Gross 1',buildingRef:'way/1',chunkId:'15/1/1',unitKey:'u1',grossPerMin:50,costPerMin:20,wagePerMin:5,busyness:2.37,wealth:1.3,appeal:65,customersPerMin:19.55,basketUnits:3.25,checkoutUsedPerMin:61.23,checkoutRatePerMin:144,dayRevenue:800}],assets:[{id:'way/1',kind:'property',label:'Offices',value:4000}],propertyAnchors:[{ref:'way/1',lon:1,lat:1}]});
let optionalFails=false,me={playerId:'person',piloting:{companyId:'co',name:'Company'}},operational=game('co'),companyFeedFails=false,partial=false;
ctx.gameGet=async p=>{
 if(p==='/me')return me;
 if(p==='/game/co'){
  if(companyFeedFails)throw Error('temporary company feed failure');
  return partial?{playerId:'co',cash:1500,income:{netPerMin:30},sectionsUnchanged:['shops','assets','propertyAnchors']}:operational;
 }
 if(p==='/game/person')return game('person');
 if(optionalFails&&p.startsWith('/company/'))throw Error('optional company API unavailable');
 if(p==='/company/mine')return{companies:[{id:'co',name:'Company',isPublic:!!me.piloting?.public}]};
 if(p==='/company/co/equity')return{isPublic:!!me.piloting?.public};
 if(p==='/company/co/members')return{members:[]};
 throw Error('optional feed unavailable');
};
(async()=>{
 let first=await vm.runInContext('refreshData()',ctx);
 assert.equal(first.accounts.company.counts.shops,1);assert.equal(first.accounts.company.assetInventory.buildings.length,1);
 assert.equal(first.identity.companyId,'co');
 const original=first.accounts.company.income.sources.shops.rows[0];
 const mappings={'unitKey:u1':1};
 me={playerId:'person',piloting:{companyId:'co',name:'Company',public:true}};
 companyFeedFails=true;
 let pub=await vm.runInContext('refreshData()',ctx);
 assert.equal(pub.diagnostics.publicCompany,'listed');assert.equal(pub.diagnostics.operationalFeed,'cached');
 assert.equal(pub.accounts.company.income.sources.shops.rows[0].id,original.id);
 assert.equal(pub.accounts.company.assetInventory.buildings.length,1);
 optionalFails=true;
 let optional=await vm.runInContext('refreshData()',ctx);
 assert.equal(optional.accounts.company.income.sources.shops.rows[0].id,'stable-1');
 assert.equal(optional.companyProfile.equity.isPublic,true);
 optionalFails=false;
 assert.equal(plan(pub.accounts.company.income.sources.shops.rows,'Gross {n}',1,mappings).changes.length,0);
 companyFeedFails=false;partial=true;
 pub=await vm.runInContext('refreshData()',ctx);
 assert.equal(pub.accounts.company.cash,1500);
 assert.equal(pub.accounts.company.income.sources.shops.rows[0].id,'stable-1');
 assert.equal(pub.accounts.company.assetInventory.buildings.length,1);
 assert.equal(plan(pub.accounts.company.income.sources.shops.rows,'Gross {n}',1,mappings).changes.length,0);
 me={playerId:'person',piloting:{company:{id:'co'},name:'Company',public:true}};
 assert.equal((await vm.runInContext('refreshData()',ctx)).identity.companyId,'co','alternate explicit company ID');
 me={playerId:'person',piloting:null};
 const personal=await vm.runInContext('refreshData()',ctx);
 assert.equal(personal.identity.companyId,null);assert.equal(personal.accounts.character.id,'person');
 assert.equal(personal.accounts.company.id,'co','available company remains visible from cached operational feed');
 assert.equal(personal.diagnostics.companyOperationalFeed,'cached');
 assert.equal(personal.identity.availableCompanies.length,1);
 await assert.rejects(vm.runInContext('performRename({id:"stable-1",name:"Gross 1"},"Other","company","co")',ctx),/matching account/,'cached company cannot authorize shop writes while unpiloted');
 me={playerId:'person',piloting:{companyId:'co',name:'Company',public:true}};
 assert.equal((await vm.runInContext('refreshData()',ctx)).accounts.company.income.sources.shops.rows[0].id,'stable-1');
 const metric=derive(operational.shops[0],{appealGrade:12,footTraffic:0.3,shoppersPerMin:2});
 assert.equal(metric.appealGrade,65);assert.equal(metric.footTraffic,2.37);assert.equal(metric.wealth,1.3);
 assert.equal(metric.customersPerMin,19.55);assert.equal(metric.basketUnits,3.25);assert.equal(metric.dayRevenue,800);
 assert.ok(Math.abs(metric.registerBusy-42.5208)<.01);
 assert.equal(derive({appeal:null,busyness:null,wealth:null},{},0).wealth,null);
 me={playerId:'person',piloting:{name:'Company'}};
 const uncertain=await vm.runInContext('refreshData()',ctx);
 assert.equal(uncertain.identity.companyId,null);assert.equal(uncertain.accounts.company.id,'co');assert.equal(uncertain.diagnostics.identity,'partial');
 me={playerId:'person'};const missingPilot=await vm.runInContext('refreshData()',ctx);
 assert.equal(missingPilot.identity.companyId,null);assert.equal(missingPilot.accounts.company.id,'co');assert.equal(missingPilot.diagnostics.identity,'partial');
 assert.equal(vm.runInContext('activeAccountFromMe({playerId:"person",piloting:{name:"Company"}}).uncertain',ctx),true,'an unidentified pilot cannot authorize a write');
 await assert.rejects(vm.runInContext('performRename({id:"stable-1",name:"Gross 1"},"New","company","co")',ctx),/matching account/);
 console.log('PASS: private to public, partial/failed operational feed, stable shops/deeds/Gross IDs, alternate account ID, personal switching, structured metrics');
})().catch(e=>{console.error(e);process.exitCode=1;});
