const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const src=fs.readFileSync(require('node:path').join(__dirname,'../content.js'),'utf8');
const shops=Array.from({length:331},(_,i)=>({shopId:`shop-${i}`,name:`Gross ${331+i}`,grossPerMin:i+1}));
const account={kind:'company',id:'company-a',income:{sources:{shops:{rows:shops}}}};
const state={page:'rename',renameLearning:null,renameTemplate:null,renamePattern:'Gross {n}',renameSortMode:'gross',renameStart:1,grossRebases:{},selected:new Set(),learnShopSelection:{},bulkPreview:[],bulkSkipped:0};
const picker={value:'shopId:shop-10'};
const learnButton={},openLearnButton={};let learned=null,opened=null,updates=0,currentOpen=null,calls=0;
const ctx=vm.createContext({state,shadow:{},CRCCRename:require('../rename-plan'),moneyExact:n=>`$${Number(n).toFixed(2)}`,esc:v=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),baseShopRows:a=>[...a.income.sources.shops.rows],shopName:r=>r.name,shopGross:r=>r.grossPerMin,visibleShopFromPage:()=>currentOpen,shopRows:()=>[shops[1]],propertyRows:()=>[],bindSearch:()=>{},render:()=>{},toast:()=>{},openShop:(a,r)=>{opened=r;},$:(selector)=>selector==='#learnShop'?picker:selector==='#learnRename'?learnButton:selector==='#learnOpenRename'?openLearnButton:null,$$:()=>[],chrome:{runtime:{sendMessage:async msg=>{calls++;learned=msg;return{ok:true,learning:{active:true,marker:'marker'}};}}}});
vm.runInContext(src.slice(src.indexOf('  function learnableShopRows('),src.indexOf('  function renderTools(')),ctx);
const html=vm.runInContext('renderRename(account)',Object.assign(ctx,{account}));
assert.match(html,/<option value="shopId:shop-330"[^>]*>Gross 661 · \$331\.00\/min<\/option>/,'highest earning shop appears first');
assert.equal((html.match(/<option value="shopId:shop-/g)||[]).length,331,'shop picker includes all 331 shops');
assert.match(html,/id="learnOpenRename"/,'learn can use the shop currently visible in the game');
vm.runInContext(src.slice(src.indexOf('  function bindDynamic(a)'),src.indexOf('  async function runScout(')),ctx);
vm.runInContext('bindDynamic(account)',ctx);
picker.onchange();
assert.equal(state.learnShopSelection['company:company-a'],'shopId:shop-10');
shops.reverse();
const rerender=vm.runInContext('renderRename(account)',ctx);
assert.match(rerender,/<option value="shopId:shop-10" selected>/,'selected game shop ID survives reordered API data');
const other={kind:'character',id:'person',income:{sources:{shops:{rows:shops}}}};
assert.equal(vm.runInContext('CRCCRename.idOf(selectedLearnShop(other))',Object.assign(ctx,{other})),'shopId:shop-330','other account does not inherit the selected shop');
(async()=>{
  currentOpen={row:shops.find(x=>x.shopId==='shop-45')};
  await openLearnButton.onclick();
  assert.equal(learned.shop.shopId,'shop-45','open game shop is learned by its stable shop ID');
  assert.equal(learned.accountId,'company-a');
  assert.equal(opened,null,'open shop does not trigger navigation');
  currentOpen={row:{shopId:'not-owned',name:'Unrelated'}};
  const before=calls;
  await openLearnButton.onclick();
  assert.equal(calls,before,'a shop outside this account cannot be learned');
  currentOpen=null;
  await learnButton.onclick();
  assert.equal(learned.kind,'startRenameLearning');
  assert.equal(learned.shop.shopId,'shop-10','Learn uses selected game ID, regardless of Shops tab filtering');
  assert.equal(opened.shopId,'shop-10');
  const shadow={activeElement:{id:'learnShop'}};
  const focused=vm.createContext({state,shadow,updateChrome:()=>{updates++;}});
  vm.runInContext(src.slice(src.indexOf('  function render(){'),src.indexOf('  function metric(')),focused);
  vm.runInContext('render()',focused);
  assert.equal(updates,1,'game data refresh does not replace an open native shop dropdown');
  console.log('PASS: learn picker sorted by gross, all shops available, account and stable-ID selection retained, correct shop learned, open dropdown survives refresh');
})().catch(e=>{console.error(e);process.exitCode=1;});
