const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const src=fs.readFileSync(require('node:path').join(__dirname,'../background.js'),'utf8');
const db={},ctx=vm.createContext({URL,Date,console,chrome:{storage:{local:{get:async()=>db,set:async patch=>Object.assign(db,patch)}}}});
vm.runInContext(src.slice(0,src.indexOf('async function recordHistory(')),ctx);
vm.runInContext(src.slice(src.indexOf('function osmLabel('),src.indexOf('// ---- live market intelligence')),ctx);
vm.runInContext(src.slice(src.indexOf('function objectWalk('),src.indexOf('async function storeObservation(')),ctx);
vm.runInContext(src.slice(src.indexOf('async function storeObservation('),src.indexOf('async function saveShopHealth(')),ctx);
const run=code=>vm.runInContext(code,ctx);
(async()=>{
  const rooms=Array.from({length:135},(_,i)=>({key:`way/42/f0/uN${i}`,kind:'room',label:'Classroom',areaM2:i%2?220:180,status:'vacant'}));
  ctx.building={ref:'way/42',label:'Observed school',areaM2:5873.29,busyness:1.64,value:2919550,archetype:'civic',subtype:'school',floors:5,usableFloors:3,owner:null,landlord:{kind:'npc',name:'School Holdings',playerId:null},rentableUnits:rooms};
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/building/inspect?ref=way%2F42',ts:1000,data:building})");
  ctx.place={displayName:'School area',lat:-20.25,lon:57.48,address:{city:'Quatre Bornes'}};
  ctx.mapData={elements:[{type:'way',id:42,tags:{building:'yes',name:'School footprint'},geometry:[{lat:-20.2499,lon:57.4799},{lat:-20.2499,lon:57.4801},{lat:-20.2501,lon:57.4801},{lat:-20.2501,lon:57.4799}]},{type:'way',id:43,tags:{building:'yes'},geometry:[{lat:-20.2498,lon:57.4798},{lat:-20.2498,lon:57.4802},{lat:-20.2502,lon:57.4802},{lat:-20.2502,lon:57.4798}]}]};
  run('overpassJson=async()=>mapData');
  const result=await run("scoutBuildings('Quatre Bornes',1000,60,place)");
  assert.equal(result.gameRows.length,1,'newly observed building must be visible in the local search');
  assert.equal(result.gameRows[0].roomCount,135);
  assert.equal(result.gameRows[0].vacantRooms,135);
  assert.equal(result.gameRows[0].vacantRoomSizes.length,135);
  assert.equal(result.gameRows[0].area,5873.29);
  assert.equal(result.gameRows[0].archetype,'civic');
  assert.equal(result.gameRows[0].subtype,'school');
  assert.equal(result.gameRows[0].usableFloors,3);
  assert.equal(result.gameRows[0].owner,null);
  assert.equal(result.gameRows[0].landlord.name,'School Holdings');
  assert.equal(result.rows.find(r=>r.ref==='way/42').gameMatch.roomCount,135,'exact OSM ref matches observed property');
  assert.equal(result.rows.find(r=>r.ref==='way/43').gameMatch,undefined,'nearby but different OSM ref must not inherit game info');
  const content=fs.readFileSync(require('node:path').join(__dirname,'../content.js'),'utf8');
  const ui=vm.createContext({finite:v=>v!=null&&v!==''&&Number.isFinite(Number(v)),num:(v,d=0)=>v!=null&&Number.isFinite(Number(v))?Number(v):d,esc:v=>String(v).replace(/</g,'&lt;'),moneyExact:v=>v==null?'—':'$'+Number(v).toFixed(2),validCoord:(a,b)=>Number.isFinite(Number(a))&&Number.isFinite(Number(b)),state:{scoutFilters:{minArea:5000,minRooms:50,minRoomArea:200,onlyObserved:false},scoutRadius:1000,scoutQuery:'Quatre Bornes',scoutSuggestions:[],scoutBusy:false,buildingIntel:db.crcc_building_intel_v4,unitIntel:db.crcc_retail_units_v1}});
  vm.runInContext(content.slice(content.indexOf('  function scoutQuality('),content.indexOf('  function renderCompany(){')),ui);
  ui.result=result;
  ui.state.scout=result;
  const filtered=vm.runInContext('filteredScoutRows(result)',ui);
  assert.equal(filtered.game.length,1);
  assert.equal(filtered.osm.length,1,'66 rooms at least 200 m² meet the room filter');
  assert.equal(filtered.osm[0].ref,'way/42');
  const html=vm.runInContext('renderScout()',ui);
  assert.match(html,/135 rooms/);
  assert.match(html,/NPC landlord: School Holdings/);
  assert.match(html,/civic · school · 5 floors · 3 usable/);
  assert.match(html,/rooms ≥200 m²/);
  assert.doesNotMatch(html,/yes · footprint/,'generic OSM building tag is hidden');
  ui.state.scoutFilters.minRooms=70;
  assert.equal(vm.runInContext('filteredScoutRows(result).game.length',ui),0);
  ui.state.scoutFilters.minArea=0;ui.state.scoutFilters.minRooms=0;ui.state.scoutFilters.minRoomArea=0;
  assert.equal(vm.runInContext('filteredScoutRows(result).osm.length',ui),2,'unobserved map leads remain when no room filter applies');
  ui.state.scoutFilters.maxRoomArea=200;
  assert.equal(vm.runInContext('filteredScoutRows(result).game.length',ui),1,'rooms at most 200 m² match inside a much larger building');
  assert.match(vm.runInContext('renderScout()',ui),/68 rooms ≤200 m²/);
  ui.state.scoutFilters.minRoomArea=200;
  assert.equal(vm.runInContext('filteredScoutRows(result).game.length',ui),0,'minimum and maximum apply to the same room');
  ui.state.scoutFilters.minRoomArea=0;ui.state.scoutFilters.maxRoomArea=500;
  ui.state.scoutFilters.maxArea=500;
  assert.equal(vm.runInContext('filteredScoutRows(result).game.length',ui),0,'building area maximum is distinct from room area maximum');
  ui.state.scoutFilters.maxArea=0;ui.state.scoutFilters.maxRoomArea=0;
  const lead={ref:'way/501',footprintM2:5000},roomBuilding={ref:'way/500',gameObserved:true,area:5000,roomCount:3,vacantRooms:2,roomSizes:[300,500,650],vacantRoomSizes:[500,650]};
  ui.roomFixture={gameRows:[roomBuilding],rows:[{ref:'way/500',gameMatch:roomBuilding},lead]};
  ui.state.scoutFilters.maxRoomArea=500;
  assert.equal(vm.runInContext('filteredScoutRows(roomFixture).game.length',ui),1);
  assert.equal(vm.runInContext('filteredScoutRows(roomFixture).osm.length',ui),1,'map lead with unknown rooms cannot pass a room-size filter');
  ui.state.scoutFilters.vacantOnly=true;
  assert.match(vm.runInContext('scoutRoomText(roomFixture.gameRows[0])',ui),/1 vacant rooms ≤500 m²/);
  ui.state.unitIntel={...ui.state.unitIntel};
  ui.state.unitIntel['way/500']={ref:'way/500',units:{
    'way/500/f0/room300':{key:'way/500/f0/room300',kind:'room',label:'Small room',areaM2:300,status:'leased',rentPerDay:20,floor:0},
    'way/500/f0/room500':{key:'way/500/f0/room500',kind:'room',label:'Vacant room',areaM2:500,status:'vacant',rentPerDay:40,floor:0},
    'way/500/f0/room650':{key:'way/500/f0/room650',kind:'room',label:'Large room',areaM2:650,status:'vacant',rentPerDay:50,floor:0}
  }};
  ui.state.scout=ui.roomFixture;
  const roomHtml=vm.runInContext('renderScout()',ui);
  assert.match(roomHtml,/View 1 matching room/);
  assert.match(roomHtml,/way\/500\/f0\/room500/);
  assert.doesNotMatch(roomHtml,/way\/500\/f0\/room300|way\/500\/f0\/room650/,'room list uses both size and vacancy filters');
  ui.state.scout=result;
  ui.state.scoutFilters.minRooms=2;
  assert.equal(vm.runInContext('filteredScoutRows(roomFixture).game.length',ui),0,'minimum count checks matching vacant rooms');
  ui.state.scoutFilters.minRooms=0;ui.state.scoutFilters.maxRooms=1;
  assert.equal(vm.runInContext('filteredScoutRows(roomFixture).game.length',ui),1,'maximum count checks matching vacant rooms');
  ui.state.scoutFilters.vacantOnly=false;
  assert.equal(vm.runInContext('filteredScoutRows(roomFixture).game.length',ui),0,'leased room counts when vacant-only is off');
  ui.state.scoutFilters.maxRooms=0;ui.state.scoutFilters.maxRoomArea=0;
  ui.state.scoutFilters.minTraffic=2;
  assert.equal(vm.runInContext('filteredScoutRows(result).game.length',ui),0,'traffic threshold uses official building data');
  ui.state.scoutFilters.minTraffic=1.5;ui.state.scoutFilters.ownership='npcLandlord';
  assert.equal(vm.runInContext('filteredScoutRows(result).game.length',ui),1);
  assert.equal(vm.runInContext('filteredScoutRows(result).osm.length',ui),1,'unobserved leads do not inherit ownership or traffic');
  ui.state.scoutFilters.ownership='playerOwner';
  assert.equal(vm.runInContext('filteredScoutRows(result).game.length',ui),0,'NPC landlord does not mean player owned');
  ctx.partial={ref:'way/42',rentableUnits:rooms.slice(0,1),busyness:1.8};
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/building/inspect?ref=way%2F42',ts:1100,data:partial})");
  assert.equal(db.crcc_building_intel_v4['way/42'].landlord.name,'School Holdings','partial response preserves landlord');
  assert.equal(db.crcc_retail_units_v1['way/42'].owner,null,'explicit owner null remains known');
  ctx.changed={ref:'way/42',rentableUnits:[],owner:{kind:'player',name:'New Owner',playerId:'id-1'},landlord:{kind:'player',name:'New Owner',playerId:'id-1'}};
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/building/inspect?ref=way%2F42',ts:1200,data:changed})");
  const updated=await run("scoutBuildings('Quatre Bornes',1000,60,place)");
  assert.equal(updated.gameRows[0].owner.playerId,'id-1','newer player ownership replaces explicit null');
  ui.state.scout=updated;
  assert.equal(vm.runInContext('filteredScoutRows(state.scout).game.length',ui),1);
  assert.match(vm.runInContext('renderScout()',ui),/Player owner: New Owner/);
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/building/inspect?ref=way%2F42',ts:900,data:building})");
  assert.equal(db.crcc_retail_units_v1['way/42'].owner.playerId,'id-1','older NPC response does not revert current owner');
  ctx.busyBuilding={ref:'way/43',label:'Busy house',archetype:'residential',subtype:'house',floors:2,usableFloors:2,areaM2:370.33,busyness:2.8,value:75700,owner:null,landlord:{kind:'npc',name:'Whitlock Holdings'},rentableUnits:[]};
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/building/inspect?ref=way%2F43',ts:1300,data:busyBuilding})");
  const ranked=await run("scoutBuildings('Quatre Bornes',1000,60,place)");
  ui.state.scout=ranked;ui.state.scoutFilters.ownership='any';ui.state.scoutFilters.minTraffic=0;ui.state.scoutSort='traffic';
  assert.equal(vm.runInContext('filteredScoutRows(state.scout).game[0].ref',ui),'way/43','Scout ranks official busyness above distance');
  assert.match(vm.runInContext('renderScout()',ui),/residential · house · 2 floors · 2 usable/);
  assert.match(vm.runInContext('renderScout()',ui),/NPC landlord: Whitlock Holdings/);
  ui.state.scoutFilters.minTraffic=2;
  assert.equal(vm.runInContext('filteredScoutRows(state.scout).game.length',ui),1);
  ui.state.scoutFilters.ownership='playerOwner';
  assert.equal(vm.runInContext('filteredScoutRows(state.scout).game.length',ui),0);
  ui.state.scoutFilters.ownership='any';ui.state.scoutFilters.minTraffic=0;ui.state.scoutSort='distance';
  assert.equal(vm.runInContext('filteredScoutRows(state.scout).game.length',ui),2);
  assert.match(content,/r\.buildingType!==['"]yes['"]/, 'generic OSM building=yes is not shown as a label');
  console.log('PASS: observed school exact OSM match, 135 room sizes, 5,000 m² and 200 m² filters, unrelated map lead excluded');
})().catch(e=>{console.error(e);process.exitCode=1;});
