const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../background.js'),'utf8');
const db={},reads=[];
const context=vm.createContext({URL,Date,console,setTimeout,clearTimeout,chrome:{storage:{local:{get:async keys=>{reads.push(keys);return Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,db[k]]));},set:async patch=>Object.assign(db,patch)}}}});
vm.runInContext(src.slice(0,src.indexOf('async function recordHistory(')),context);
vm.runInContext(src.slice(src.indexOf('function osmRefParts('),src.indexOf('async function overpassJson(')),context);
vm.runInContext(src.slice(src.indexOf('function osmLabel('),src.indexOf('// ---- live market intelligence')),context);
vm.runInContext(src.slice(src.indexOf('function objectWalk('),src.indexOf('async function storeObservation(')),context);
vm.runInContext(src.slice(src.indexOf('async function storeObservation('),src.indexOf('async function saveShopHealth(')),context);
const run=code=>vm.runInContext(code,context);
(async()=>{
 const place={displayName:'Test City',lat:35,lon:129,address:{city:'Test City'}};context.place=place;
 const props=[];for(let i=0;i<12000;i++)props.push({ref:`way/${10000+i}`,label:'Other place',area:50000,lat:45,lon:140});
 props.push({ref:'way/1',label:'Large building with small room',area:5100,lat:35,lon:129,footTraffic:2,roomSizes:[480,1500],vacantRoomSizes:[480],roomCount:2,vacantRooms:1,price:1000000});
 props.push({ref:'way/2',label:'Small building with big room',area:600,lat:35,lon:129,footTraffic:1.2,roomSizes:[600],vacantRoomSizes:[],roomCount:1,vacantRooms:0});
 db.crcc_scout_index_v1=Object.fromEntries(props.map(x=>[x.ref,x]));db.crcc_scout_accounts_v1={};db.crcc_scout_parcels_v1={};db.crcc_osm_ref_cache_v1={};
 let mapCalls=0;context.mapData={elements:[{type:'way',id:1,tags:{building:'yes'},geometry:[{lat:35,lon:129},{lat:35,lon:129.0001},{lat:35.0001,lon:129.0001}]},{type:'way',id:3,tags:{building:'yes'},geometry:[{lat:35,lon:129},{lat:35,lon:129.0001},{lat:35.0001,lon:129.0001}]}]};
 context.fetchMap=async()=>{mapCalls++;return context.mapData;};run('overpassJson=fetchMap');
 const noFilters=await run("scoutBuildings('Test City',1000,60,place)");assert.equal(noFilters.gameRows.length,2);assert.equal(noFilters.rows.length,2);assert.equal(mapCalls,1);
 reads.length=0;const repeat=await run("scoutBuildings('Test City',1000,60,place)");assert.equal(repeat.diagnostics.mapRequests,0);assert.equal(repeat.diagnostics.mapCacheHits,1);assert.equal(repeat.diagnostics.rawProperties,0);assert.equal(repeat.diagnostics.resultCacheHit,true);assert.equal(mapCalls,1,'identical search reuses normalized results');
 assert(!reads.flat().includes('crcc_snapshot_v4')&&!reads.flat().includes('crcc_retail_units_v1')&&!reads.flat().includes('crcc_building_intel_v4'),'warm scout reads no account snapshots or unit rosters');
 const small=await run("scoutBuildings('Test City',1000,60,place,{maxRoomArea:500,vacantOnly:true})");assert.equal(small.gameRows.length,1,'small room survives despite large parent building');assert.equal(small.gameRows[0].ref,'way/1');assert.equal(small.rows.length,0,'no unrelated map leads on room search');assert.equal(small.diagnostics.mapRequests,0);
 const big=await run("scoutBuildings('Test City',1000,60,place,{minArea:5000})");assert.equal(big.gameRows.length,1);assert.equal(big.gameRows[0].ref,'way/1');assert(big.diagnostics.rejectedDistance>=12000);assert(big.diagnostics.rejectedArea>=1);assert.equal(big.diagnostics.fullyEvaluated,1);assert.equal(mapCalls,1);
 const traffic=await run("scoutBuildings('Test City',1000,60,place,{minTraffic:1.5})");assert.equal(traffic.gameRows.length,1);assert.equal(traffic.rows.length,0);assert.equal(mapCalls,1);
 // A changed observation updates only its ref and retains the old room roster when partial.
 context.partial={ref:'way/1',areaM2:5100,busyness:2.3,rentableUnits:[{key:'way/1/f0/room',kind:'room',areaM2:480,status:'vacant'}]};
 await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/building/detail',ts:1234,data:partial})");
 assert.equal(db.crcc_scout_index_v1['way/1'].footTraffic,2.3);assert.equal(db.crcc_scout_index_v1['way/1'].roomSizes[0],480);
 const updated=await run("scoutBuildings('Test City',1000,60,place,{maxRoomArea:500})");assert.equal(updated.gameRows[0].footTraffic,2.3);assert(updated.diagnostics.rawProperties>0,'observation invalidates result cache');
 // Two concurrent searches must share one in-flight map request.
 let release;context.fetchMap=()=>{mapCalls++;return new Promise(r=>release=r);};run('overpassJson=fetchMap');
 const newPlace={displayName:'Nearby',lat:35.001,lon:129,address:{}};context.newPlace=newPlace;
 const a=run("scoutBuildings('Nearby',1000,60,newPlace)"),b=run("scoutBuildings('Nearby',1000,60,newPlace)");
 await new Promise(r=>setTimeout(r,0));assert.equal(mapCalls,2);release(context.mapData);await Promise.all([a,b]);assert.equal(mapCalls,2);
 db.crcc_scout_index_v1['way/4']={ref:'way/4',label:'Official room',area:6000,roomSizes:[500],vacantRoomSizes:[500]};
 context.centerPlace={displayName:'Room area',lat:36,lon:130,address:{}};
 context.fetchMap=async query=>{mapCalls++;assert.match(query,/out center;/);return{elements:[{type:'way',id:4,center:{lat:36,lon:130},tags:{building:'yes'}}]};};run('overpassJson=fetchMap');
 const center=await run("scoutBuildings('Room area',1000,60,centerPlace,{maxRoomArea:500})");assert.equal(center.gameRows[0]?.ref,'way/4');assert.equal(center.rows.length,0);assert.equal(center.diagnostics.mapRequests,1);
 const content=fs.readFileSync(path.join(__dirname,'../content.js'),'utf8');
 const uiState={scoutQuery:'First',scoutRadius:1000,scoutFilters:{},scoutPlace:null,scoutBusy:false,scout:null,scoutSuggestions:[]};
 const pending=[];const ui=vm.createContext({state:uiState,clearTimeout,setTimeout,URLSearchParams,location:{search:''},console,render:()=>{},toast:()=>{},chrome:{runtime:{sendMessage:()=>new Promise(resolve=>pending.push(resolve))}}});
 vm.runInContext('let scoutFilterTimer=null,scoutGeneration=0;'+content.slice(content.indexOf('  function scheduleScout('),content.indexOf('\n',content.indexOf('  function scheduleScout(')))+'\n'+content.slice(content.indexOf('  async function runScout()'),content.indexOf('\n',content.indexOf('  async function runScout()'))),ui);
 const first=vm.runInContext('runScout()',ui);uiState.scoutQuery='Second';const second=vm.runInContext('runScout()',ui);
 pending[1]({ok:true,result:{place:{displayName:'Second'}}});await second;pending[0]({ok:true,result:{place:{displayName:'First'}}});await first;
 assert.equal(uiState.scout.query,'Second','obsolete network completion cannot overwrite newer search');assert.equal(uiState.scoutBusy,false);
 uiState.scoutFilters={};uiState.scout.gameRows=[{ref:'a',footTraffic:1,price:10,distanceM:50},{ref:'b',footTraffic:3,price:5,distanceM:10}];uiState.scout.rows=[];
 ui.finite=v=>v!=null&&v!==''&&Number.isFinite(Number(v));ui.num=(v,d=0)=>ui.finite(v)?Number(v):d;uiState.buildingIntel={};uiState.unitIntel={};
 vm.runInContext(content.slice(content.indexOf('  function scoutOwnership('),content.indexOf('  function scoutBuildingDetails(')),ui);
 uiState.scoutSort='traffic';assert.equal(vm.runInContext('filteredScoutRows(state.scout).game[0].ref',ui),'b');
 uiState.scoutSort='value';assert.equal(vm.runInContext('filteredScoutRows(state.scout).game[0].ref',ui),'a');assert.equal(pending.length,2,'local sorting makes no network request');
 uiState.scoutQuery='Third';uiState.scoutFilters.maxArea=500;
 vm.runInContext('scheduleScout();scheduleScout();scheduleScout()',ui);
 await new Promise(r=>setTimeout(r,240));assert.equal(pending.length,3,'rapid filter changes debounce to one request');pending[2]({ok:true,result:{gameRows:[],rows:[]}});
 console.log('PASS: no filters, small rooms in large buildings, large building, traffic, center lookup, repeat cache, no account roster reads, partial observation, request dedupe, sorting, debounce, stale search ignored');
})().catch(e=>{console.error(e);process.exitCode=1;});
