const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const src=fs.readFileSync(require('node:path').join(__dirname,'../background.js'),'utf8');
const db={};
const ctx=vm.createContext({URL,Date,console,chrome:{storage:{local:{get:async()=>db,set:async changes=>Object.assign(db,changes)}}}});
vm.runInContext(src.slice(0,src.indexOf('async function recordHistory(')),ctx);
vm.runInContext(src.slice(src.indexOf('function osmLabel('),src.indexOf('// ---- live market intelligence')),ctx);
vm.runInContext(src.slice(src.indexOf('function objectWalk('),src.indexOf('async function storeObservation(')),ctx);
vm.runInContext(src.slice(src.indexOf('async function storeObservation('),src.indexOf('async function saveShopHealth(')),ctx);
const run=code=>vm.runInContext(code,ctx);
(async()=>{
  const a={id:'parcel-a',chunkId:'15/1/2',centroid:[129.056,35.183],areaM2:2174,busyness:1.48,cityProximity:.52,value:9000,owner:null,polygon:[[129,35]]};
  const b={id:'parcel-b',chunkId:'15/1/2',centroid:[129.057,35.184],areaM2:1019,busyness:1.76,value:10000,owner:{id:'someone',name:'A player'}};
  ctx.response={parts:[{chunks:{},same:['15/1/2']},{chunks:{'15/1/2':{chunkId:'15/1/2',parcels:[a,b,a]}},same:[]},{chunks:{},same:['15/1/2']}]};
  assert.equal(run('extractScoutParcels(response).length'),2);
  assert.equal(run('extractScoutParcels({parts:[{chunks:{},same:["15/1/2"]}]}).length'),0);
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/world/chunks',ts:1000,data:response})");
  assert.equal(Object.keys(db.crcc_scout_parcels_v1).length,2);
  assert.equal(db.crcc_scout_parcels_v1['parcel-a'].owner,null);
  assert.equal(db.crcc_scout_parcels_v1['parcel-b'].owner.name,'A player');
  assert.equal(db.crcc_observed_v4['/world/chunks'].data.chunkIds.length,1);
  assert.equal(JSON.stringify(db.crcc_observed_v4).includes('polygon'),false,'avoid storing map polygons twice');
  await run("storeObservation({kind:'response',method:'POST',status:200,url:'https://play.capitalrift.com/api/world/chunks',ts:1001,data:response})");
  assert.equal(Object.keys(db.crcc_scout_parcels_v1).length,2,'read-only chunk POST response is observed without a new request');
  await run("storeObservation({kind:'response',method:'POST',status:200,url:'https://play.capitalrift.com/api/game/me/rename',ts:1002,data:response})");
  assert.equal(db.crcc_observed_v4['/game/me/rename'],undefined,'unrelated write responses are ignored');
  ctx.partial={parts:[{chunks:{'15/1/2':{chunkId:'15/1/2',parcels:[{id:'parcel-a',centroid:[129.056,35.183],busyness:1.6}]}}}]};
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/world/chunks',ts:1100,data:partial})");
  assert.equal(db.crcc_scout_parcels_v1['parcel-a'].owner,null);
  assert.equal(db.crcc_scout_parcels_v1['parcel-a'].areaM2,2174);
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/world/chunks',ts:900,data:response})");
  assert.equal(db.crcc_scout_parcels_v1['parcel-a'].busyness,1.6,'older chunk must not overwrite newest parcel');
  ctx.clear={parts:[{chunks:{'15/1/2':{chunkId:'15/1/2',parcels:[{id:'parcel-b',centroid:[129.057,35.184],owner:null}]}}}]};
  await run("storeObservation({kind:'response',method:'GET',status:200,url:'https://play.capitalrift.com/api/world/chunks',ts:1200,data:clear})");
  assert.equal(db.crcc_scout_parcels_v1['parcel-b'].owner,null,'explicitly unowned on newer game response');
  ctx.place={displayName:'Busan',lat:35.183,lon:129.056,address:{city:'Busan',country:'Korea'}};
  run('overpassJson=async()=>({elements:[]})');
  const result=await run("scoutBuildings('Busan',1000,60,place)");
  assert.equal(result.parcelRows.length,2);
  assert.equal(result.parcelRows[0].id,'parcel-b','highest traffic first');
  assert.equal(result.gameRows.length,0,'parcel scouting must not add land to owned/game property rows');
  ctx.far={displayName:'Elsewhere',lat:40,lon:10,address:{}};
  assert.equal((await run("scoutBuildings('Elsewhere',1000,60,far)" )).parcelRows.length,0);
  const content=fs.readFileSync(require('node:path').join(__dirname,'../content.js'),'utf8');
  const ui=vm.createContext({Date,finite:v=>v!=null&&Number.isFinite(Number(v)),esc:v=>String(v).replace(/</g,'&lt;'),moneyExact:v=>v==null?'—':'$'+Number(v).toFixed(2)});
  vm.runInContext(content.slice(content.indexOf('  function renderScoutParcels('),content.indexOf('  function renderScout(){')),ui);
  ui.result=result;
  const html=vm.runInContext('renderScoutParcels(result)',ui);
  assert.match(html,/highest traffic first/);
  assert.match(html,/Unowned when observed/);
  assert.match(html,/tpParcelScout/);
  console.log('PASS: official chunk parcel IDs, same dedupe, partial/stale/owner transitions, distance and traffic ordering, no ownership inference');
})().catch(e=>{console.error(e);process.exitCode=1;});
