const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../background.js'),'utf8'),R=require('../region-data.js');
const db={crcc_snapshot_v4:{accounts:{character:{id:'personal/id',income:{sources:{shops:{rows:[{id:'shop/?#'}]}}}},company:{id:'company/id',income:{sources:{shops:{rows:[{id:'co shop'}]}}}}}}};
const calls=[],observed=[],ctx=vm.createContext({URL,Date,console,CRCCRegionData:R,chrome:{storage:{local:{get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,db[k]])),set:async rows=>Object.assign(db,rows)}}}});
vm.runInContext(source.slice(0,source.indexOf('async function recordHistory(')),ctx);
vm.runInContext(source.slice(source.indexOf('async function verifiedReadAccount('),source.indexOf('// ---- 5-minute automatic refresh ----')),ctx);
let me={playerId:'personal/id',piloting:null};ctx.gameGet=async url=>{calls.push(url);if(url==='/me')return me;if(url.includes('/region-info/at?'))return{areaId:'12/946/1652',chunkId:'15/7573/13222',activityArea:{businesses:2},busyness:2,wealth:1.3};if(url.includes('/shop-history?'))return{shopId:url.includes('co%20shop')?'co shop':'shop/?#',days:[{day:1,revenue:1,units:2,items:{}}]};throw Error('unexpected URL '+url);};
ctx.storeObservation=async obs=>observed.push(obs);
(async()=>{
 const regionPerson=await vm.runInContext('loadRegionInfo("character","personal/id",-75.17394,39.93027)',ctx);
 assert.equal(regionPerson.areaId,'12/946/1652');assert(calls.includes('/game/personal%2Fid/region-info/at?lon=-75.17394&lat=39.93027'));
 db.crcc_region_info_v1={'personal/id:12/946/1652':{...regionPerson,lon:-75.17394,lat:39.93027,observedAt:Date.now()}};
 const regionCalls=calls.filter(url=>url.includes('/region-info/at?')).length;
 await vm.runInContext('loadRegionInfo(\"character\",\"personal/id\",-75.17394,39.93027)',ctx);
 assert.equal(calls.filter(url=>url.includes('/region-info/at?')).length,regionCalls,'same location reuses areaId-keyed cache');
 const historyPerson=await vm.runInContext('loadShopHistory("personal/id","shop/?#","character")',ctx);
 assert.equal(historyPerson.shopId,'shop/?#');assert(calls.includes('/game/personal%2Fid/shop-history?shopId=shop%2F%3F%23'));
 const before=calls.length;await assert.rejects(vm.runInContext('loadRegionInfo("company","company/id",1,2)',ctx),/matching account/);await assert.rejects(vm.runInContext('loadShopHistory("company/id","co shop","company")',ctx),/matching account/);assert.equal(calls.length,before+2,'unpiloted company only receives identity checks, not operational requests');
 me={playerId:'personal/id',piloting:{companyId:'company/id'}};
 await vm.runInContext('loadRegionInfo("company","company/id",126.848,-37.56)',ctx);
 assert(calls.includes('/game/company%2Fid/region-info/at?lon=126.848&lat=-37.56'));
 await vm.runInContext('loadShopHistory("company/id","co shop","company")',ctx);
 assert(calls.includes('/game/company%2Fid/shop-history?shopId=co%20shop'));
 const beforeStale=calls.length;await assert.rejects(vm.runInContext('loadRegionInfo("company","old-company",1,2)',ctx),/matching account/);await assert.rejects(vm.runInContext('loadShopHistory("personal/id","shop/?#","character")',ctx),/matching account/);assert.equal(calls.length,beforeStale+2);
 await assert.rejects(vm.runInContext('loadRegionInfo("company","company/id","not-a-coordinate",2)',ctx),/valid Capital Rift location/);
 assert.equal(observed.length,4,'only four explicit successful requests were cached');
 assert(!/loadRegionInfo\(/.test(source.slice(source.indexOf('async function maybeAutoRefresh('),source.indexOf('chrome.runtime.onMessage.addListener('))),'refresh alarm never requests Region Info');
 console.log('PASS: personal/company verified URL encoding, direct Shop History GET, stale/unpiloted account refusal, no Region Info polling');
})().catch(e=>{console.error(e);process.exitCode=1});
