const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const content=fs.readFileSync(path.join(__dirname,'../content.js'),'utf8');
const state={scout:null,scoutSurvey:null,scoutSurveyFilters:null,scoutStatus:'idle',scoutMessage:'',scoutViewport:null,scoutSelected:null,data:null,landBuyTemplate:null,landBuyLearning:null,landBuySession:null,landBuySelected:new Set(),landBuyMaxSpend:'',landBuyMaxParcels:100,landBuyStrategy:'current',landBuyPriceTolerance:0};
const ctx=vm.createContext({state,console,Date,Math,Number,setTimeout,clearTimeout,esc:v=>String(v).replace(/</g,'&lt;'),moneyExact:v=>'$'+Number(v).toFixed(2),money:v=>'$'+Number(v).toFixed(0),num:(v,d=0)=>v!=null&&Number.isFinite(Number(v))?Number(v):d,finite:v=>v!=null&&Number.isFinite(Number(v)),account:()=>({id:'company-a',kind:'company'}),validCoord:(lat,lon)=>Number.isFinite(Number(lat))&&Number.isFinite(Number(lon)),render:()=>{},window:{postMessage(){}},chrome:{runtime:{sendMessage:async()=>({})}}});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../scout-survey.js'),'utf8'),ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../land-buyer.js'),'utf8'),ctx);
state.scoutSurveyFilters=vm.runInContext('CRCCScoutSurvey.empty()',ctx);
vm.runInContext(content.slice(content.indexOf('  function roomTargetPanel(){'),content.indexOf('  function renderDeals(){')),ctx);
vm.runInContext(content.slice(content.indexOf('  function scoutViewportChanged('),content.indexOf('  function renderCompany(){')),ctx);
const html=()=>vm.runInContext('renderScout()',ctx);
assert.match(html(),/Survey Visible Area/);assert.match(html(),/Pan or zoom the CapitalRift map/);assert.doesNotMatch(html(),/id="scoutQuery"/);
state.scoutSurvey={viewport:{north:1,south:0,east:1,west:0},stats:{chunksLoaded:1,partialCoverage:true},entities:[],status:'no-game-data'};state.scoutStatus='no-game-data';assert.match(html(),/No captured CapitalRift entities/);
state.scoutSurvey.entities=[{ref:'way/123',label:'Building',entityType:'building',areaM2:10000,busyness:2,owner:{kind:'npc'},lat:.5,lon:.5,source:'observed-game-building'}];state.scoutSurvey.status='ready';state.scoutStatus='ready';assert.match(html(),/1 matches from 1 game entities/);
state.scoutSurveyFilters=vm.runInContext('CRCCScoutSurvey.active({target:"room",roomMax:500,vacant:true})',ctx);assert.match(html(),/No matches from 1 game entities/);assert.match(html(),/rejected by type 1/);
state.scoutSurvey.stats.detailsRemaining=12;assert.match(html(),/12 building details still need inspection/);assert.match(html(),/Inspect more room details/);delete state.scoutSurvey.stats.detailsRemaining;
state.scoutSurveyFilters=vm.runInContext('CRCCScoutSurvey.active({target:"building",roomMax:500,vacant:true})',ctx);assert.match(html(),/1 matches from 1 game entities/);assert.doesNotMatch(html(),/id="roomMax"/);
assert.doesNotMatch(html(),/surveySelect|>Select</);assert.match(html(),/Open area in game/);
state.scoutSurveyFilters=vm.runInContext('CRCCScoutSurvey.active({target:"room"})',ctx);assert.match(html(),/value="200"[^>]*>200 m²/);
state.scoutSurvey.entities=[{ref:'way/123/f0/room',entityType:'room',label:'Room',lat:.5,lon:.5,locationPrecision:'chunk'}];
assert.match(html(),/Find room in game/);
state.scoutRoomTarget={ref:'way/123/f0/room',parentRef:'way/123',label:'Room',buildingLabel:'Main building',floor:0,areaM2:200};
assert.match(html(),/Main building/);assert.match(html(),/way\/123\/f0\/room/);assert.match(html(),/Find exact room in open game panel/);
state.scoutRoomTarget=null;
state.scoutStatus='viewport-changed';state.scoutMessage='';assert.match(html(),/Map moved/);
state.scoutStatus='ready';state.scoutMessage='';state.scoutSurveyFilters=vm.runInContext('CRCCScoutSurvey.active({target:"land",availability:"purchasable"})',ctx);state.scoutSurvey.entities=[{ref:'parcel/a',entityType:'land',label:'Land parcel A',areaM2:5000,busyness:2,listing:{kind:'sale',forSale:true,price:125000},owner:null,lat:.5,lon:.5,source:'observed-game-land',observedAt:Date.now()}];assert.match(html(),/Mass land buyer/);assert.match(html(),/class="landSelect"/);assert.match(html(),/sale \$125000\.00/);
state.scoutSurveyFilters=vm.runInContext('CRCCScoutSurvey.active({target:"land"})',ctx);
const unknown={ref:'78021580-7110-8325-bce1-800280040000',entityType:'land',label:'Land parcel 78021580',areaM2:8898.999,value:2125,owner:null,listing:null,lat:.5,lon:.5,source:'observed-game-land',observedAt:Date.now()};
state.scoutSurvey.entities=[unknown];const candidateHtml=html();assert.match(candidateHtml,/NEEDS DETAILS/);assert.match(candidateHtml,/Learn Purchase Action/);
assert.match(candidateHtml,/class="landSelect"[^>]*data-ref="78021580-7110-8325-bce1-800280040000"[^>]*>/,'unresolved game land checkbox is enabled');
assert.doesNotMatch(candidateHtml,/class="landSelect"[^>]*disabled/);
state.landBuySelected.add(unknown.ref);assert.match(html(),/Selected candidates<\/span><b>1/);assert.match(html(),/1 selected still need a confirmed offer/);
unknown.myOwned=true;vm.runInContext('pruneLandSelection()',ctx);assert.equal(state.landBuySelected.size,0,'confirmed owned parcel is removed from batch selection');assert.match(html(),/ALREADY OWNED/);
assert.match(content,/tpCoords\(row\.lat,row\.lon,row\.label,false\)/,'scout navigation is read only and independent of account ownership');
console.log('PASS: initial, no game data, matches, rejected filters, 200 m² rooms, direct navigation, stale-map status, mass land buyer UI');
