const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../background.js'),'utf8');
const db={},reads=[];
const ctx=vm.createContext({URL,Date,console,setTimeout,clearTimeout,chrome:{storage:{local:{get:async keys=>{reads.push(keys);return Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,db[k]]));},set:async v=>Object.assign(db,v)}}}});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../scout-survey.js'),'utf8'),ctx);
vm.runInContext(src.slice(0,src.indexOf('async function recordHistory(')),ctx);
vm.runInContext(src.slice(src.indexOf('function osmLabel('),src.indexOf('// ---- live market intelligence')),ctx);
vm.runInContext(src.slice(src.indexOf('function objectWalk('),src.indexOf('async function storeObservation(')),ctx);
vm.runInContext(src.slice(src.indexOf('async function storeObservation('),src.indexOf('async function saveShopHealth(')),ctx);
vm.runInContext('var observationWrites=Promise.resolve();',ctx);
const run=x=>vm.runInContext(x,ctx);
(async()=>{
 const tile=run("scoutTileBounds('15/21617/18265')");assert(tile.north>tile.south);
 const midLat=(tile.north+tile.south)/2,midLon=(tile.east+tile.west)/2;
 const view={north:midLat+.0006,south:midLat-.0006,east:midLon+.0006,west:midLon-.0006,zoom:16};ctx.view=view;
 const center=[midLon,midLat],polygon=[[midLon+.00055,midLat],[midLon+.0013,midLat],[midLon+.0013,midLat+.0004]];
 ctx.chunk={parts:[{chunks:{'15/21617/18265':{chunkId:'15/21617/18265',buildings:[{ref:'way/123',label:'Real building',areaM2:120000,busyness:2.2,value:900000,owner:{kind:'npc',name:'Landlord'},lat:midLat,lon:midLon,rentableUnits:[{key:'way/123/f0/room',kind:'room',areaM2:480,status:'vacant',rentPerDay:500}]}],parcels:[{id:'parcel/1',chunkId:'15/21617/18265',centroid:center,polygon,areaM2:500,busyness:1.3,owner:null}]}}}]};
 await run("storeObservation({kind:'response',method:'POST',status:200,url:'https://play.capitalrift.com/api/world/chunks',ts:10000,data:chunk})");
 assert.equal(db.crcc_scout_chunks_v1['15/21617/18265'].buildingRefs[0],'way/123');
 assert.equal(db.crcc_scout_index_v1['way/123'].area,120000);assert.equal(db.crcc_retail_units_v1['way/123'].units['way/123/f0/room'].rentPerDay,500);
 ctx.partial={parts:[{chunks:{'15/21617/18265':{chunkId:'15/21617/18265',parcels:[]}}}]};
 await run("storeObservation({kind:'response',method:'POST',status:200,url:'https://play.capitalrift.com/api/world/chunks',ts:11000,data:partial})");
 assert.equal(db.crcc_scout_chunks_v1['15/21617/18265'].buildingRefs[0],'way/123','partial parcel-only chunk retains official building refs');
 reads.length=0;const result=await run('surveyVisibleArea(view)');
 assert.equal(result.status,'ready');assert.equal(result.stats.chunksLoaded,1);assert.equal(result.entities.length,3);
 assert(!reads.flat().includes('crcc_snapshot_v4')&&!reads.flat().includes('crcc_shop_stock_v1'));
 reads.length=0;assert.equal((await run('surveyVisibleArea(view)')).stats.cached,true);assert.equal(reads.length,0,'same viewport reuses a complete survey snapshot');
 reads.length=0;const buildingsOnly=await run("surveyVisibleArea(view,{target:'building'})");
 assert.equal(buildingsOnly.entities.length,1);assert.equal(buildingsOnly.entities[0].entityType,'building');
 assert(!reads.flat().includes('crcc_scout_parcels_v1'),'building search never reads land records');
 assert(reads.flat().filter(k=>String(k).startsWith('crcc_scout_unit_v1:')).length<=1,'building search reads only observed unit records');
 reads.length=0;const landOnly=await run("surveyVisibleArea(view,{target:'land'})");
 assert.equal(landOnly.entities.length,1);assert.equal(landOnly.entities[0].entityType,'land');
 assert(!reads.flat().includes('crcc_scout_index_v1')&&!reads.flat().some(k=>String(k).startsWith('crcc_scout_unit_v1:')),'land search never reads building index or unit records');
 reads.length=0;const roomsOnly=await run("surveyVisibleArea(view,{target:'room'})");
 assert(roomsOnly.entities.length>0&&roomsOnly.entities.every(e=>e.entityType==='room'));
 assert(!reads.flat().includes('crcc_scout_parcels_v1'),'room search never reads parcel cache');
 const originalAnchor=db.crcc_scout_index_v1['way/123'];
 db.crcc_scout_index_v1['way/123']={...originalAnchor,lat:null,lon:null,footprintBounds:null};
 const nearby=await run("computeVisibleArea(view,{target:'room'})");
 const roomLocation=nearby.entities.find(e=>e.ref==='way/123/f0/room');
 assert.equal(roomLocation.locationPrecision,'chunk');
 assert.equal(roomLocation.lat,midLat,'a room without a precise footprint can open the observed game chunk vicinity');
 db.crcc_scout_index_v1['way/123']=originalAnchor;
 db.crcc_scout_index_v1['way/123']={...originalAnchor,chunkId:'15/21618/18265',lat:null,lon:null,footprintBounds:null};
 const fallbackBuilding=await run("computeVisibleArea(view,{target:'building',roomsMin:0})");
 assert(fallbackBuilding.entities.some(e=>e.ref==='way/123'&&e.entityType==='building'),'building-only Deals use observed unit records when the index anchor is outside the requested chunks');
 assert(fallbackBuilding.entities.every(e=>e.entityType==='building'),'building-only surveys do not emit units');
 db.crcc_scout_index_v1['way/123']=originalAnchor;
 ctx.requested={...view,source:'game-land-request',chunkIds:['15/21617/18265'],cameraPoint:{x:100,y:200}};
 const byGame=await run('surveyVisibleArea(requested)');assert.equal(byGame.stats.chunksRequested,1);assert.equal(byGame.stats.chunksLoaded,1);assert.equal(byGame.viewport.cameraPoint.x,100);
 ctx.sameChunksMoved={...ctx.requested,cameraPoint:{x:150,y:200}};const reused=await run('surveyVisibleArea(sameChunksMoved)');assert.equal(reused.stats.cached,undefined,'failed building-chunk reads are not cached as complete');assert.equal(reused.viewport.cameraPoint.x,150,'retry uses the latest camera snapshot');
 ctx.other={...ctx.requested,chunkIds:['15/21618/18265']};assert.equal((await run('surveyVisibleArea(other)')).stats.chunksLoaded,0,'requested chunk IDs, not approximate bounds, control coverage');
 ctx.entities=result.entities;
 const filtered=run("CRCCScoutSurvey.filter(entities,{target:'room',roomMax:500,vacant:true,availability:'rentable'},view)");assert.equal(filtered.matches.length,1);assert.equal(filtered.matches[0].rentPerDay,500,'NPC-owned vacant room is rentable');
 assert.equal(run("CRCCScoutSurvey.filter(entities,{target:'room',rentMax:500,ownership:'npc'},view).matches.length"),1);
 ctx.npcLandlord={...result.entities.find(e=>e.entityType==='room'),owner:null,landlord:{kind:'npc',name:'Whitlock Holdings'}};
 assert.equal(run("CRCCScoutSurvey.filter([npcLandlord],{target:'room',ownership:'npc'},view).matches.length"),1,'game NPC landlord is recognized when owner is null');
 assert.equal(run("CRCCScoutSurvey.filter(entities,{target:'room',rentMin:1000},view).stats.rejected.value"),1);
 assert.equal(run("CRCCScoutSurvey.filter(entities,{target:'building',buildingMin:100000,roomMax:10,vacant:true},view).matches.length"),1,'irrelevant room filters cannot hide large building');
 assert.equal(run("CRCCScoutSurvey.filter(entities,{target:'land',buildingMin:200000,roomMax:10,vacant:true},view).matches.length"),1,'land ignores room and building criteria');
 assert.equal(run("CRCCScoutSurvey.filter(entities,{target:'land',landMin:1000},view).matches.length"),0);
 assert.equal(run("CRCCScoutSurvey.filter(entities,{target:'land',availability:'purchasable'},view).matches.length"),0,'null owner is not proof that land is purchasable');
 assert.equal(run("CRCCScoutSurvey.filter(entities,{target:'any'},view).matches.length"),3);
 assert.equal(run("CRCCScoutSurvey.filter(entities,{target:'room',roomMax:500,sort:'area'},view).matches.length"),1);
 const corrected=run("CRCCScoutSurvey.active({target:'building',buildingMin:5000,buildingMax:500,roomMax:500,vacant:true})");assert.equal(corrected.buildingMax,5000);assert.equal(corrected.roomMax,null);assert.equal(corrected.vacant,false);
 assert.equal(run("CRCCScoutSurvey.active({target:'building',roomsMin:5}).roomsMin"),5,'building room-count controls remain active');
 assert.equal(run("CRCCScoutSurvey.active({target:'land',rentMax:25,buildingMin:5000,roomMax:500}).buildingMin"),null);
 const edge={ref:'edge',entityType:'land',lat:midLat,lon:midLon+.001,footprintBounds:{north:midLat+.0001,south:midLat-.0001,west:midLon+.0005,east:midLon+.0015}};ctx.edge=edge;
 assert.equal(run('CRCCScoutSurvey.intersects(edge,view)'),true,'partially visible property included despite center outside');
 // A room survey refreshes only observed canonical building refs, never land
 // parcels or synthetic vector-tile identities. The second survey reuses them.
 ctx.newTile={chunkId:'15/21617/18265',buildings:[{ref:'way/456',lat:midLat,lon:midLon,label:'New building'},{ref:'tile/15/21617/18265/9',lat:midLat,lon:midLon}]};
 await run('storeScoutMapTile(newTile,Date.now())');
 const cachedNew=db.crcc_scout_index_v1['way/456'];
 db.crcc_scout_index_v1['way/456']={...cachedNew,lat:undefined,lon:undefined,footprintBounds:undefined,at:Date.now()+20000,label:'Observed detail'};
 ctx.lateTile={chunkId:'15/21617/18265',buildings:[{ref:'way/456',lat:midLat,lon:midLon,footprintBounds:{north:midLat+.0001,south:midLat-.0001,east:midLon+.0001,west:midLon-.0001}}]};
 await run('storeScoutMapTile(lateTile,Date.now())');
 assert.equal(db.crcc_scout_index_v1['way/456'].label,'Observed detail','later map geometry preserves newer detail name');
 assert.equal(db.crcc_scout_index_v1['way/456'].lat,midLat,'older chunk can enrich missing coordinates without replacing newer details');
 const detailCalls=[];ctx.gameGet=async url=>{detailCalls.push(url);const ref=new URL(url,'https://play.capitalrift.com/api').searchParams.get('ref');return {ref,label:'Fresh building',areaM2:8000,rentableUnits:[{key:`${ref}/f0/room`,kind:'room',areaM2:450,status:'vacant',rentPerDay:550}]};};
 const fresh=await run("surveyVisibleArea(requested,{target:'room',roomMin:250,roomMax:500})");
 assert(fresh.entities.some(e=>e.ref==='way/456/f0/room'),'targeted building detail produces a room');
 assert(fresh.entities.every(e=>e.entityType==='room'),'room survey never emits land, buildings or shop units');
 assert(detailCalls.some(url=>url.includes('way%2F456')),'uses the observed building-info query');
 assert(!detailCalls.some(url=>url.includes('tile%2F')),'synthetic tile feature cannot be used as a building-info ref');
 const count=detailCalls.length;
 await run("surveyVisibleArea(requested,{target:'room',roomMin:250,roomMax:500})");
 assert.equal(detailCalls.length,count,'repeat room survey reuses normalized details');
 assert(!reads.flat().includes('crcc_snapshot_v4'),'targeted detail never reads the full account snapshot');
 const content=fs.readFileSync(path.join(__dirname,'../content.js'),'utf8');vm.runInContext(content.slice(content.indexOf('  function scoutViewportChanged('),content.indexOf('\n',content.indexOf('  function scoutViewportChanged('))),ctx);
 ctx.shifted={...view,north:view.north+.002,south:view.south+.002};assert.equal(run('scoutViewportChanged(view,shifted)'),true,'surveyed bounds remain the stale-state baseline');
 const denseChunk=db.crcc_scout_chunks_v1['15/21617/18265'],savedRefs=denseChunk.buildingRefs;
 denseChunk.buildingRefs=[...savedRefs,...Array.from({length:10001},(_,i)=>`way/${100000+i}`)];
 reads.length=0;
 assert((await run("computeVisibleArea(view,{target:'building'})")).entities.some(e=>e.ref==='way/123'),'dense chunks still return indexed building deals');
 assert((await run("computeVisibleArea(view,{target:'any'})")).entities.some(e=>e.ref==='way/123/f0/room'),'dense chunks retain previously observed rooms');
 assert(!reads.some(keys=>Array.isArray(keys)&&keys.length>10000),'dense chunks do not trigger an unbounded unit cache read');
 denseChunk.buildingRefs=savedRefs;
 ctx.far={north:0.001,south:-0.001,east:0.001,west:-0.001};assert.equal((await run('surveyVisibleArea(far)')).status,'no-game-data');
 await assert.rejects(run('surveyVisibleArea({north:0,south:0,east:0,west:0})'));
 console.log('PASS: game chunk POST, viewport tile, building/room/land, NPC rent, area dependencies, unknowns, edge intersection, no-game-data, no account reads');
})().catch(e=>{console.error(e);process.exitCode=1;});
